#!/usr/bin/env bash
# One run: preflight the seller/deployer wallet, deploy + seed on Monad testnet,
# regenerate the ABI handoff files. Usage: scripts/deploy.sh
set -euo pipefail
cd "$(dirname "$0")/.."

set -a; source contracts/.env; set +a
SELLER_ADDR=$(cast wallet address --private-key "$SELLER_PRIVATE_KEY")

BALANCE=$(cast balance "$SELLER_ADDR" --rpc-url "$RPC_URL")
MIN=$(cast to-wei 12)
if [ "$(python3 -c "print(1 if int('$BALANCE') < int('$MIN') else 0)")" = "1" ]; then
  echo "Seller/deployer $SELLER_ADDR holds $(cast from-wei "$BALANCE") MON."
  echo "Send it ~15 MON (keep it above Monad's 10 MON reserve floor) and re-run."
  exit 1
fi

(cd contracts && forge script script/DeployAndSeed.s.sol --rpc-url monad_testnet --broadcast)

(cd contracts && forge inspect DigitalEscrow abi --json > ../shared/DigitalEscrow.abi.json)
python3 - <<'EOF'
import json
abi = json.load(open('shared/DigitalEscrow.abi.json'))
with open('shared/abi.ts', 'w') as f:
    f.write('// Generated by scripts/deploy.sh from forge inspect — do not edit by hand.\n')
    f.write('export const escrowAbi = ' + json.dumps(abi, indent=2) + ' as const;\n')
EOF

echo "Done. Handoff files: shared/escrow.ts, shared/DigitalEscrow.abi.json, shared/deployments.json"
